### ISSUE TITLE
[EPIC] Add support for sampling traces

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1144]
Currently SigNoz doesn't enable sampling of traces. Enabling sampling would allow organizations which can potentially generate huge trace data to sample it so that resource requirements are optimised

Tasks:

- [x] Blocker for sampling: https://github.com/SigNoz/signoz/issues/1793
- [x] https://github.com/SigNoz/signoz/issues/2151
- [x] https://github.com/SigNoz/engineering-pod/issues/641
- [ ] https://github.com/SigNoz/signoz/issues/1667
- [ ] Docs: https://github.com/SigNoz/signoz/issues/1800

**Comment by makeavish** [comment]
PRD issue: https://github.com/SigNoz/engineering-pod/issues/441

**Comment by ankitnayan** [comment]
we can start with commented settings in otel-collector and docs for head-based sampling

**Comment by ankitnayan** [comment]
https://opensearch.org/blog/technical-post/2021/12/distributed-tracing-pipeline-with-opentelemetry/

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues/1800

**Comment by srikanthccv** [comment]
We might not do this one our end, at least in foreseeable future. Hence closing.
