### ISSUE TITLE
[EPIC] - Enable easy integrations from the UI

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1430]
- [ ] https://github.com/SigNoz/signoz/issues/1429
- [ ] mongodb
- [ ] memcached
- [ ] mysql
- [ ] kafka
- [ ] https://github.com/SigNoz/signoz/issues/1837
- [ ] https://github.com/SigNoz/signoz/issues/1447
- [ ] https://github.com/SigNoz/signoz/issues/3685
