### ISSUE TITLE
[EPIC] Cost Control of Observability data

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#2064]
- [ ] Show ingestion rate and cardinality of metrics
- [ ] Drop rules for metrics
- [ ] Sampling rules for traces
- [ ] Sampling rules for logs
- [ ] Query analysis and insights
