### ISSUE TITLE
[EPIC]FE(Trace)Query Builder

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2315]
This is the list of items that needed to be completed to get the first version of trace explorer working based on the PRD. The issues are ordered to reflect the development process of the traces explorer. Each issue will be independently worked on, and after merging, the explorer's state will have the working functionality until that point. 

- [x] https://github.com/SigNoz/signoz/issues/2317
- [x] https://github.com/SigNoz/signoz/issues/2314
- [x] https://github.com/SigNoz/signoz/issues/2286
- [x] https://github.com/SigNoz/signoz/issues/2306
- [x] https://github.com/SigNoz/signoz/issues/2307
- [x] https://github.com/SigNoz/signoz/issues/2312
- [x] https://github.com/SigNoz/signoz/issues/2308
- [x] https://github.com/SigNoz/signoz/issues/2309
- [x] https://github.com/SigNoz/signoz/issues/2310
- [x] https://github.com/SigNoz/signoz/issues/2313
- [x] #2332
- [x] #2335
- [x] #2336
- [x] #2333
- [x] #2334
- [x] #2337
- [x] #2338
- [x] #2339
