### ISSUE TITLE
[EPIC]FE(Logs)Query Builder

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2340]
- [ ] https://github.com/SigNoz/signoz/issues/2322
- [ ] https://github.com/SigNoz/signoz/issues/2306
- [ ] https://github.com/SigNoz/signoz/issues/2307
- [ ] https://github.com/SigNoz/signoz/issues/2312
- [ ] Multiple query management in the logs explorer
- [ ] Timeline view for the logs explorer
- [ ] List view tab in the logs explorer
- [ ] Time series view tab in the logs explorer
- [ ] Table view tab in the logs explorer
- [ ] Ability to save the logs explorer page query result to dashboard
- [ ] Ability to create an alert from the logs explorer page

**Comment by srikanthccv** [comment]
@palashgdev go through the traces/metrics/logs frontend query builder and close the issues which are completed.
