### ISSUE TITLE
[EPIC]FE(Metrics)Query Builder

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2349]
- [ ] https://github.com/SigNoz/signoz/issues/2319
- [ ] https://github.com/SigNoz/signoz/issues/2314
- [ ] https://github.com/SigNoz/signoz/issues/2286
- [ ] https://github.com/SigNoz/signoz/issues/2306
- [ ] https://github.com/SigNoz/signoz/issues/2307
- [ ] https://github.com/SigNoz/signoz/issues/2312
- [ ] https://github.com/SigNoz/signoz/issues/2309
- [ ] https://github.com/SigNoz/signoz/issues/2313
- [ ] https://github.com/SigNoz/signoz/issues/2350
- [ ] Time series view tab in the metrics explorer
- [ ] https://github.com/SigNoz/signoz/issues/2351
- [ ] https://github.com/SigNoz/signoz/issues/2352
