### ISSUE TITLE
[EPIC]FE(Dashboards)Query Builder

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2353]
- [x] https://github.com/SigNoz/signoz/issues/2314
- [x] https://github.com/SigNoz/signoz/issues/2286
- [x] https://github.com/SigNoz/signoz/issues/2306
- [x] https://github.com/SigNoz/signoz/issues/2307
- [x] https://github.com/SigNoz/signoz/issues/2312
- [x] https://github.com/SigNoz/signoz/issues/2308
- [x] https://github.com/SigNoz/signoz/issues/2309
- [x] https://github.com/SigNoz/signoz/issues/2310
- [x] https://github.com/SigNoz/signoz/issues/2313
- [x] https://github.com/SigNoz/signoz/issues/2587
- [x] https://github.com/SigNoz/signoz/issues/2354
- [x] https://github.com/SigNoz/signoz/issues/2355
- [x] https://github.com/SigNoz/signoz/issues/2356
- [x] https://github.com/SigNoz/signoz/issues/2357

**Comment by srikanthccv** [comment]
1. Aggregate Operator:

    <img width="75" alt="Screenshot 2023-04-22 at 4 33 18 PM" src="https://user-images.githubusercontent.com/22846633/233780263-0a5f0d32-c61f-43d6-8570-e8d5ecc18924.png">
   
   - The entire operator should be visible, and it's hard to see what these indicate.
   - Make it searchable - this can be done entirely on the frontend since the list is static.
   - The `NOOP` operator shouldn't be in the dropdown for traces/logs for panel 
     types `graph`, `value` and `table`. But, It is allowed for the panel type `list`. Implement with this
     detail in mind.
   - The list of allowed operators for `graph`, `value` and `table` panel types.
      - <details><summary>Traces</summary> ["count", "count_distinct", "sum", "avg", "min", "max", "p05", "p10", "p20", "p25", "p50", "p75", "p90", "p95", "p99", "rate", "rate_sum", "rate_avg", "rate_min", "rate_max"] </details>
      - <details><summary>Logs</summary> ["count", "count_distinct", "sum", "avg", "min", "max", "p05", "p10", "p20", "p25", "p50", "p75", "p90", "p95", "p99", "rate", "rate_sum", "rate_avg", "rate_max", "rate_min"] </details>
      - <details><summary>Metrics</summary> ["noop", "count", "count_distinct", "sum", "avg", "min", "max", "p05", "p10", "p20", "p25", "p50", "p75", "p90", "p95", "p99", "rate", "sum_rate", "rate_sum", "rate_avg", "rate_min", "rate_max", "hist_quantile_50", "hist_quantile_75", "hist_quantile_90", "hist_quantile_95", "hist_quantile_99"] </details>

2. Aggregate Attribute
    - The placeholder name for
       - Metrics: Metric name
       - Logs: Aggregate attribute
       - Traces: Aggregate attribute

3. Filter
     <img width="809" alt="Screenshot 2023-04-22 at 5 16 56 PM" src="https://user-images.githubusercontent.com/22846633/233782842-d6c2b449-c3ce-4881-b98d-6be09d38ba0e.png">
     - For Logs/Traces, Filter should be enabled in all cases, regardless of the aggregate attribute. It appears that it is only enabled after some aggregate attribute is selected. 
     - For Metrics, WHERE should be enabled when the metric name is selected
     - The ability to select a custom key with ENTER is not working as it does for the key from the API. For example, type the text "serv"; there will be three options "serv", "service_name", and "service_name". I can select the "service_name" and "service_namespace" with the cursor or ENTER but not the "serv".
     - For the operators such as (`=`, `!=` basically everything except `in`, `nin` ) where the value is single, the selection of value by mouse pointer click or ENTER should make the chip without further action.
     - The space after the filter operator (i.e.`=`,`!=`, `contains`, `in` etc.) should not be mandatory. Anything after the operator can be considered a value. 
     - For a key type `int64`/`float64`, only allow number(s), single number for every operator except `in`, `nin` and one or more number comma separate for `in` and `nin`.
     - Value search doesn't work for the operators `in` and `nin`
     - Clicking on the edit chip without modifying the currently focused edit chip makes it disappear, to be more explicitly when one clicks on edit for `operation=http` and then clicks on the other chip `, service_name=driver` makes the `operation=http` chip completely disappears
     - There is an unnecessary `,` at the end of the chip when the selected filter operator is `in`/`nin.`
     - The value itself may contain the `,` in it, i.e. value could be `HTTP,grpc`, and that should be handled.
     - `/attribute_values` is not sending `filterAttributeKey`, `filterAttributeKeyDataType` and `tagType` for the key selected. If the key is a custom key, send null values for them.
     - Unnecessary API calls are being made to `/attribute_keys` when the user is typing text for value filtering.
     - Don't make too many API calls in a short period.

4. Group by
     - For Traces/Logs, group by should be enabled without any pre-requisite on the aggregate attribute selection.
     - For Metrics, enable group by when the metric name is selected.

5. Limit
     - Only positive integer values should be allowed for limit. It currently accepts double/floats.

6. Having
     - Having is not present in the metrics
     - Things Yevhen wanted to but postponed
7. Order by
     - Change in the aggregate operator or aggregate attribute should only remove the `OP(attribute) asc/desc`. It currently removes all, including those from the group by.
     - Removing a key from the group by should remove its corresponding order by item. For example, If the user group by "method", "code", and order by selected as "method asc", "code desc", when "method" is removed from the group by, it should remove "method asc" from the order by.
 
8. Run Query
     - There could be a loader on the button area when the API call is made (enhancement suggested in a recent review).  

9. Legend formatting
     - The client should format the legend using the "labels" part of the API response.

**Comment by srikanthccv** [comment]
Couple more issues found

- [ ] ClickHouse query tab shows an error (because of the incorrect `queryType`, it should `clickhouse_sql`).
- [ ] PromQL tab also shows an error (because of the incorrect `queryType`, it should `promql`)

- [ ] X-axis time and hover time are incorrect. Is this an issue with the time format? 
<img width="791" alt="Screenshot 2023-05-09 at 4 52 17 PM" src="https://github.com/SigNoz/signoz/assets/22846633/ce3fdd28-eab4-4796-bf89-cbf2688f9cc3">

- [ ] Legend formatting not working for formula

- [ ] When the formula is created, there should be an ability to disable a query. Currently, it is not supported. I can't disable `A` in the following. 
<img width="811" alt="Screenshot 2023-05-09 at 4 57 40 PM" src="https://github.com/SigNoz/signoz/assets/22846633/a8663b12-3157-4b21-80c5-40db0f613e17">
