### ISSUE TITLE
EPIC: Add resource attributes filtering support for exceptions list page

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2483]
- [ ] https://github.com/SigNoz/signoz/issues/2484
- [ ] https://github.com/SigNoz/signoz-otel-collector/issues/119
- [ ] https://github.com/SigNoz/signoz/issues/2485
