### ISSUE TITLE
Logs Explorer [EPIC]

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2752]
- [ ] https://github.com/SigNoz/signoz/issues/2747
- [ ] https://github.com/SigNoz/signoz/issues/2748
- [ ] https://github.com/SigNoz/signoz/issues/2749
- [ ] https://github.com/SigNoz/signoz/issues/2750
- [ ] https://github.com/SigNoz/signoz/issues/2751

**Comment by srikanthccv** [comment]
@palashgdev, there is an epic already https://github.com/SigNoz/signoz/issues/2340 with a description for each issue instead of just a screenshot. We reassign and update them.

**Comment by palashgdev** [comment]
Closing in favour of #2340
