### ISSUE TITLE
[Epic] [LOGS] Easier self-serve logs pipeline editing with previews

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#2854]
For someone to build a pipeline using the pipeline builder they have to do a lot of hit and trial and is also not the correct way to do it as it will result back and forth between otel-collector logs and pipeline builder.

We need a system in the UI where we can provide some sample logs (can be from filtered data) and check how a pipeline parses it. This will give idea to the user regarding what to expect.

### Related Documents
- [PRD](https://www.notion.so/signoz/Pipeline-Preview-PRD-07186e602e014628baeaa047e8f8e2d8)
- [Work Breakdown Exploration](https://www.notion.so/signoz/Work-Items-Pipelines-Preview-PRD-95a532c1c0c848d898abbe16a66c7c19)

### Related Issues
- [x] https://github.com/SigNoz/signoz/issues/3028
- [x] https://github.com/SigNoz/signoz/issues/3506
- [x] https://github.com/SigNoz/signoz/issues/3507
- [x] https://github.com/SigNoz/signoz/issues/3509

**Comment by ankitnayan** [comment]
@rkssisodiya which of the issues in this EPIC is done? Please close them
