### ISSUE TITLE
[EPIC] Explorer pages v2 tasks

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3129]
- [x] https://github.com/SigNoz/signoz/issues/3080
- [x] https://github.com/SigNoz/signoz/issues/2599
- [x] https://github.com/SigNoz/signoz/issues/3067
- [x] https://github.com/SigNoz/signoz/issues/2822
- [x] https://github.com/SigNoz/signoz/issues/3133
- [x] https://github.com/SigNoz/signoz/issues/3073
- [x] https://github.com/SigNoz/signoz/issues/3111
- [x] https://github.com/SigNoz/signoz/issues/3113
- [x] https://github.com/SigNoz/signoz/issues/2842
- [x] https://github.com/SigNoz/signoz/issues/1958
- [x] https://github.com/SigNoz/signoz/issues/3154
- [x] Improved Telemetry
- [x] https://github.com/SigNoz/signoz/issues/3173
