### ISSUE TITLE
[EPIC] Dashboard improvements

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3573]
- [ ] https://github.com/SigNoz/signoz/issues/3568
- [ ] https://github.com/SigNoz/signoz/issues/3569
- [ ] https://github.com/SigNoz/signoz/issues/3570
- [ ] https://github.com/SigNoz/signoz/issues/3571
- [ ] https://github.com/SigNoz/signoz/issues/3572

**Comment by srikanthccv** [comment]
Should the backend throw an error if any update call from frontend tries to wipe out the `layout` or `widgets` from the payload? Can we assume any update from the client can only remove a maximum of one panel and throw an error otherwise? Ideally, the bug that causes this should be fixed. Meanwhile, preventing the destruction action seems like a better thing to do. It's a very poor experience and frustrating to see the whole dashboard disappear from end-user POV.

**Comment by ankitnayan** [comment]
>client can only remove a maximum of one panel 

this can be too restrictive. The issue seems to wipe out the dashboard. Should we enable a backend check of wiping all panels till we are able to reproduce?

**Comment by srikanthccv** [comment]
I don't think it's restrictive. Is there a way one can remove multiple panels at the same time (i.e. in the same request) today?

**Comment by ankitnayan** [comment]
hmm. I don't think it can be done today. We can implement it then.
We can create an issue to remove this later.

**Comment by makeavish** [comment]
@palashgdev Please close issues which are merged already.

**Comment by makeavish** [comment]
Can we also fix https://github.com/SigNoz/signoz/issues/3736 as part of the improvements?

**Comment by palashgdev** [comment]
> Can we also fix #3736 as part of the improvements?

we don't know the use case as of now

**Comment by makeavish** [comment]
> > Can we also fix #3736 as part of the improvements?
> 
> we don't know the use case as of now I am assuming this is fixed in latest version as there were useEffect not it is not the case

@srikanthccv Can you confirm if it's fixed in latest version? Can we close the issue?

**Comment by srikanthccv** [comment]
We don't know how to reproduce the issue to test if it is fixed or not.

**Comment by srikanthccv** [comment]
@palashgdev, please share the response format you mentioned that works well for clients. For any form of breaking changes it's better we introduce now because we can't do the same after we publish the API response which has growing demand.

**Comment by prashant-shahi** [comment]
@ankitnayan Can this be included as well? https://github.com/SigNoz/signoz/issues/3216

**Comment by ankitnayan** [comment]
> @ankitnayan Can this be included as well? #3216

yes

**Comment by srikanthccv** [comment]
> @palashgdev, please share the response format you mentioned that works well for clients. For any form of breaking changes it's better we introduce now because we can't do the same after we publish the API response which has growing demand.

@palashgdev @YounixM please take some time to work on this so that we can discuss and finalise it. We are going to make some changes to request payload as well.

**Comment by ankitnayan** [comment]
<img width="746" alt="Screenshot 2024-02-01 at 11 37 55 PM" src="https://github.com/SigNoz/signoz/assets/12460410/5c72e220-adc1-4d41-b966-0858f2059080">
<img width="743" alt="Screenshot 2024-02-01 at 11 38 37 PM" src="https://github.com/SigNoz/signoz/assets/12460410/c278492c-73d5-4dde-87fd-3c2da6548090">

**Comment by AshwinBhatkal** [comment]
Closing this one
Other than these 2 - https://github.com/SigNoz/signoz/issues/4611 & https://github.com/SigNoz/signoz/issues/4605, all other issues have been closed
