### ISSUE TITLE
[Epic] Log Parsing Pipeline Issues 

### ISSUE THREAD

**Issue by raj-k-singh** [SigNoz/signoz#3791]
With completion of pipeline preview work and deployment of opamp managed otel collector, log parsing pipelines are now almost ready to be released to users.
This epic tracks the blocking bugs/cleanups that must be resolved before log parsing pipelines are ready for release to users.

### Related Documents
- [all known issues](https://www.notion.so/signoz/Other-Known-Issues-3a1de1d5a42b45a19cefd31bd14914bd) 

[Part of the larger issue for enabling log parsing from the UI](https://github.com/SigNoz/signoz/issues/1779)

### Must haves
- [x] https://github.com/SigNoz/signoz/issues/3792
- [x] https://github.com/SigNoz/signoz/issues/3794
- [x] https://github.com/SigNoz/signoz/issues/3795
- [x] https://github.com/SigNoz/signoz/issues/3797
- [x] https://github.com/SigNoz/signoz/issues/3845
- [x] https://github.com/SigNoz/signoz/issues/3793
- [x] https://github.com/SigNoz/signoz/issues/3884
- [x] https://github.com/SigNoz/signoz/issues/3922
- [x] https://github.com/SigNoz/signoz/issues/3965
- [x] https://github.com/SigNoz/signoz/issues/3967
- [x] https://github.com/SigNoz/signoz/issues/3915
- [x] https://github.com/SigNoz/signoz/issues/4063
- [x] https://github.com/SigNoz/signoz/issues/4061
- [x] https://github.com/SigNoz/signoz/issues/4060
- [x] https://github.com/SigNoz/signoz/issues/3796
- [ ] https://github.com/SigNoz/signoz/issues/4020
- [ ] https://github.com/SigNoz/signoz/issues/3952
- [ ] https://github.com/SigNoz/signoz/issues/3921
- [x] https://github.com/SigNoz/signoz/issues/3981
- [x] https://github.com/SigNoz/signoz/issues/3876
- [x] https://github.com/SigNoz/signoz/issues/3914
- [ ] https://github.com/SigNoz/signoz/issues/4117
- [ ] https://github.com/SigNoz/signoz/issues/4118
- [ ] https://github.com/SigNoz/signoz/issues/4119
- [ ] https://github.com/SigNoz/engineering-pod/issues/1112

### Maybe
- [ ] https://github.com/SigNoz/signoz/issues/3798
- [ ] https://github.com/SigNoz/signoz/issues/3799
- [ ] https://github.com/SigNoz/signoz/issues/3887
- [ ] https://github.com/SigNoz/signoz/issues/3868
- [ ] https://github.com/SigNoz/signoz/issues/3859
- [ ] https://github.com/SigNoz/signoz/issues/3916

## Features
- [ ] pipelines as code
- [ ] showing version diff in the product
- [ ] showing createdBy and editedBy in the product

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues/3885

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues/4444
https://github.com/SigNoz/signoz/issues/4298
https://github.com/SigNoz/signoz/issues/4199
https://github.com/SigNoz/signoz/issues/4176

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues/2857

**Comment by ankitnayan** [comment]
## Friction Points
1. https://signoz-team.slack.com/archives/C07446MCZ5X/p1720311710480109
2. https://signoz-team.slack.com/archives/C05AXQL92BT/p1719327238156559?thread_ts=1719325651.300039&cid=C05AXQL92BT
3. https://signoz-team.slack.com/archives/C05BGMUDS1L/p1718199767089559

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues?q=is%3Aopen+is%3Aissue+label%3A%22log+pipelines%22

**Comment by pranay01** [comment]
@raj-k-singh can you create a new epic with remaining issues and close this epic ticket?
