### ISSUE TITLE
[EPIC] - Logs Improvements

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3826]
- [ ] Keyboard compatibility
- [ ] https://github.com/SigNoz/signoz/issues/3821
- [ ] https://github.com/SigNoz/signoz/issues/3513
- [ ] https://github.com/SigNoz/signoz/issues/3685
- [ ] https://github.com/SigNoz/signoz/issues/3661

**Comment by YounixM** [comment]
https://github.com/SigNoz/signoz/issues/3513 - In Review

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues/5619

**Comment by vikrantgupta25** [comment]
https://github.com/SigNoz/engineering-pod/issues/1655

**Comment by vikrantgupta25** [comment]
https://github.com/SigNoz/signoz/issues/5502

**Comment by pranay01** [comment]
@ankitnayan will the remaining items in this EPIC be picked up soon? 
Might be good to create a new EPIC with only the remaining tasks
