### ISSUE TITLE
[EPIC] - APM improvements

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3901]
- [ ] JVM, Runtime metrics https://github.com/SigNoz/signoz/issues/1964
- [ ] DB client metrics
- [ ] Http client metrics
- [ ] Java http server metrics. `http_` metrics
- [ ] Kafka consumer and producer metrics

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/engineering-pod/issues/1299

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues/3904

**Comment by pranay01** [comment]
Include story on service versioning and deployment markers
