### ISSUE TITLE
[EPIC]: dashboard time range improvements

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#4324]
Enhancements

- [ ] https://github.com/SigNoz/signoz/issues/4321
- [ ] https://github.com/SigNoz/signoz/issues/4322
- [ ] https://github.com/SigNoz/signoz/issues/4323

**Comment by mSounak-stapleio** [comment]
Hi @srikanthccv, Any update on the timeline for this? Will be a massive help if we could filter logs to the seconds.
