### ISSUE TITLE
[Epic] Create sharable URL in all pages

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#444]
- [x] #554
 - [x] Prepare the default time in the local-storage #481 (we are not using)
 - [x] Create a Sharable URL
 - [x] https://github.com/SigNoz/signoz/issues/2158
 - [ ] Refresh Icon Placement
 - [ ] Component Level Loading in All Pages
