### ISSUE TITLE
[EPIC]: Logs new schema

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#5555]
- [x] Otel collector changes: https://github.com/SigNoz/signoz-otel-collector/pull/348
  - [x] Write to new logs_v2 table and logs_v2_resource_bucket table
  - [x] Use maps for attributes and resource attributes, and added token_bf index 
  - [x] use `number` instead of int64 and float64
  - [x] use ngram index for body
  - [ ] ~~Update tags to use number instead of int64 and float64, breaking change~~
- [x] Query service changes: https://github.com/SigNoz/signoz/pull/5528
  - [x] Body search case insensitive and uses ngram
  - [x] even though tags are int64 and float64, they are converted to number.
  - [x] Any different orderby other than timestamp should use the new table.
  - [x] ~~Any different orderby (resource) should be added as a where clause in resource filter. (OR)~~ (since coverd by groupBy)
  - [x] Any different groupby (resource) should be added as a where clause in resource filter. (OR)
  - [x] Use proper indexes in resource filter 
  - [x] Proper indexes for attributes/resource attributes for the table ( case insensitive)
  - [ ] ~~Number support in tag attribute API's~~
- [x] Frontend Changes
  - [ ] ~~Support for number type~~
---
Decisions to be taken
- [ ] How should we handle group by, as of now if there are two fields in group by , we add exists filter with `AND` while filtering for it in resources, we can use `OR` here, if we don't use then no filtering will be done. ref:- https://github.com/SigNoz/signoz/pull/5420
- [x] As of now the otel collector writes to two table, the logs_v2 and logs. logs is the old table with order by timestamp, id. Should we keep it the same or create a materialized view for it ?

    We have moved on from logs and will be just using logs_v2
- [x] Do we even require materialized columns ?

     Yes only for group by 
- [x] Should filtering on attributes be case independent? decision = yes.

**Comment by nityanandagohain** [comment]
Few changes
- [ ] Since `number` type on tag_attrbutes will require frontend changes, keeping it as float64 and then in qs we are mapping it to number.
- [ ] Add lower case indexing to the resource fingerprint labels.

**Comment by nityanandagohain** [comment]
Decision w.r.t index

* Go ahead with case sensitive for attributes
* Remove minmax index and only keep bloom filter.

Create issues on clickhouse.

**Comment by nityanandagohain** [comment]
- [ ] remove resource filtering from main table.
- [ ] check index support for `in` and create issue for frontend changes to remove from logs detail.

**Comment by nityanandagohain** [comment]
https://github.com/SigNoz/signoz/issues/5614

**Comment by nityanandagohain** [comment]
This left in new schema

- [ ] FE change to use `=` instead of `in` https://github.com/SigNoz/signoz/issues/5597
- [ ] Minmax Index on numbers don't work  (clickhouse limitation)
- [ ] Attribute search is case sensitive, while resources and body search is case insensitive.  ( clickhouse limitation)
- [ ] Migration plan for old users
     - [ ] Users who are still using `_` attributes
     - [ ] Users who are not using any `_` attributes or the normal ones
     - [ ] Users who have a very high TTL set-up with tiered storage
- [ ] Default materialized column if any required? (not a blocker or much linked with this issue) 
     
  cc @ankitnayan @raj-k-singh  please add if you think anything else. (apart from JSON search which will be addressed separately)

**Comment by nityanandagohain** [comment]
Closing this  we can decide on what to do with https://github.com/SigNoz/signoz/pull/5420 later.
