### ISSUE TITLE
[EPIC] Trace Detail Page Improvements

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#5711]
- [ ] Show events
- [ ] Ability to load 10K spans. Improve frontend perf
- [ ] level up and level down features
- [ ] Better grouping of attributes
- [ ] Ability to filter and group by attributes

**Comment by ankitnayan** [comment]
https://www.notion.so/signoz/PRD-Trace-Details-Page-Improvement-e918451acce142109ab7447e42ba9320?pvs=4

**Comment by nityanandagohain** [comment]
[ ] Check how we can improve the flamegraph - DD provides ability to zoom in/zoom out in the flamegraph.
[ ] The traversal in the waterfall is a bit clunky and not very smooth.

---
Take inspirate from chome network tab - smoothness.

cc @YounixM  @aks07
