### ISSUE TITLE
[EPIC] Trace Performance Improvements

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#5713]
- [ ] Group by traceID. Sample queries at https://signoz.io/docs/tutorial/writing-clickhouse-queries-in-dashboard/
- [x] How to support searching by columns like `msgSystem` or `messaging.system` together? Today users get confused whether to use either of these in filtering and groupby. Also, if we decide to use custom column names to support semantic convention of attributes like `messaging.system`, should we use alias to still make `msgSystem` work to help backward compatibility?
- [x] Flatten Resource attributes? Also, remove from map to save storage
- [x] Search by messaging, http, db and other group attributes. Flatten these or introduce grouping?
- [x] SigNoz/engineering-pod#1886
- [ ] #6160
- [x] How to make search by resource attributes faster?
- [x] Add `env` in sorting key
- [x] We only need `signoz_spans` table to view trace detail page. If searching by traceID is fast enough in the `signoz_index_v2` table we can remove the `signoz_spans` table
- [x] Will we still need `signoz_spans` table for group by `traceID` features like trace funnels, time between producer and consumer span?
- [ ] Which schema will be best for support trace analytics like tree, map etc?
- [ ] Which schema will be best for searching in parent and child spans? @eKuG https://github.com/SigNoz/signoz/issues/3085 and https://github.com/SigNoz/signoz/issues/6013

**Comment by nityanandagohain** [comment]
Tasks

- [ ] https://github.com/SigNoz/signoz-otel-collector/issues/420

**Comment by nityanandagohain** [comment]
Things remaining

- [ ] script for migration of OLD data.
- [ ] OSS release docs for migration
- [ ] Docs for writing custom clickhouse queries.
- [ ] Migration of queries.

**Comment by nityanandagohain** [comment]
New needs
- [ ] Creation of temporary signoz_spans table with ordery by timestamp for TTL data migration
- [ ] Adding support for smartTraceAlgo in the new schema as right now that is not implemented in the new schema.

**Comment by nityanandagohain** [comment]
Closing this, there is one issue attached to this but it's not really realted ro perf
