### ISSUE TITLE
[EPIC] Data rendering limitations in product

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#5761]
- [ ] Services → Service Overview - Key Operations (List can get pretty big and cause slow down of the panel)
- [ ] Trace Explorer → Quick Filters
- [ ] Traces → Trace Details → Trace detail page number of spans
- [ ] Logs Explorer → Large Time frame → Frequency Chart
- [ ] Dashboards → Listing will get slower as we have more dashboards - Pagination is not implemented here.
- [ ] Dashboards → Time Series Panel → More data points, the slower the render 
- [ ] Dashboards → Table Panel → The large number of rows can cause problems
- [ ] Dashboards → Bar chart → Same as time series chart, more series/data points, the slower the render 
- [ ] Dashboards → Pie chart panel → More data points, the slower the render 
- [ ] Dashboards → In View Panels * Time Series Data → Even when the number of data points is comparatively less, rendering a lot of time series panels can take a lot of time and give a jittering experience. 
- [ ] Dashboard → Variables → Dependent Variables can lead to multiple Query range API triggers and combined with the above issues, it will further degrade the performance.
- [ ] Alerts - Triggered Alerts - Not paginated
- [ ] Service Map - As the number of services increases, the render will be slower due to, need to improve perceived performance.

**Comment by SagarRajput-7** [comment]
Handed over the research doc regarding performance and data limit tuned. https://www.notion.so/signoz/uPlot-Deep-Performance-Report-1acfcc6bcd198175914bd3099756e941?source=copy_link

Now pending on solutioning and decision on this - @srikanthccv to come back
