### ISSUE TITLE
[EPIC] Make the trace-explorer page more useful

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#5842]
- [x] https://github.com/SigNoz/signoz/issues/5861
- [ ] Allow filtering RootSpans, serviceEntry spans, any span https://github.com/SigNoz/signoz/issues/6013, https://github.com/SigNoz/signoz/issues/3085
- [ ] https://github.com/SigNoz/signoz/issues/3174
- [x] https://github.com/SigNoz/engineering-pod/issues/1755
- [x] https://github.com/SigNoz/engineering-pod/issues/1820
- [ ] https://github.com/SigNoz/signoz/issues/6063
- [ ] https://github.com/SigNoz/engineering-pod/issues/1667
- [ ] https://github.com/SigNoz/engineering-pod/issues/1390
- [ ] https://github.com/SigNoz/signoz/issues/5713
- [ ] Show heatmap of latency and count as axes
- [ ] Show if a span is anomalous
- [ ] Breakdown by other attributes to figure the outlier attribute 
- [ ] Show me the attributes which are common to selected spans with >p90 latency and having errors

PRD at https://www.notion.so/signoz/Trace-Explorer-Improvements-103fcc6bcd198042b644f3ab3626deba?pvs=4

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues/6013
