### ISSUE TITLE
[Epic] Infrastructure Monitoring

### ISSUE THREAD

**Issue by rahulkeswani101** [SigNoz/signoz#6134]
# Hosts List View

- [ ] Add a new tab in the side nav to show Infrastructure Monitoring.
- [ ]  Add the explore filter options to the page and add tabs for navigating to Hosts and Kubernetes.
- [ ]  Show the list view and add pagination to the records.

# Hosts Detail View

- [ ] Add the Drawer on click of the record.
- [ ] Add sub-tabs in the drawer and show the respective data.
