### ISSUE TITLE
[EPIC] query builder improvements

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#6695]
- [ ] https://github.com/SigNoz/signoz/issues/6657
- [ ] https://github.com/SigNoz/signoz/issues/6594
- [ ] https://github.com/SigNoz/signoz/issues/6556
- [ ] https://github.com/SigNoz/signoz/issues/6525
- [ ] https://github.com/SigNoz/signoz/issues/6472
- [ ] https://github.com/SigNoz/signoz/issues/6456
- [ ] https://github.com/SigNoz/signoz/issues/6393
- [ ] https://github.com/SigNoz/signoz/issues/6373
- [ ] https://github.com/SigNoz/signoz/issues/6364
- [ ] https://github.com/SigNoz/signoz/issues/6338
- [ ] https://github.com/SigNoz/signoz/issues/6317
- [ ] https://github.com/SigNoz/signoz/issues/6312
- [ ] https://github.com/SigNoz/signoz/issues/6205
- [ ] https://github.com/SigNoz/signoz/issues/6202
- [ ] https://github.com/SigNoz/signoz/issues/6195
- [ ] https://github.com/SigNoz/signoz/issues/6193
- [ ] https://github.com/SigNoz/signoz/issues/6147
- [ ] https://github.com/SigNoz/signoz/issues/6063
- [ ] https://github.com/SigNoz/signoz/issues/6015
- [ ] https://github.com/SigNoz/signoz/issues/6013
- [ ] https://github.com/SigNoz/signoz/issues/6012
- [ ] https://github.com/SigNoz/signoz/issues/6011
- [ ] https://github.com/SigNoz/signoz/issues/5981
- [ ] https://github.com/SigNoz/signoz/issues/5950
- [ ] https://github.com/SigNoz/signoz/issues/5949
- [ ] https://github.com/SigNoz/signoz/issues/5874
- [ ] https://github.com/SigNoz/signoz/issues/5873
- [ ] https://github.com/SigNoz/signoz/issues/5862
- [ ] https://github.com/SigNoz/signoz/issues/5842
- [ ] https://github.com/SigNoz/signoz/issues/5818
- [ ] https://github.com/SigNoz/signoz/issues/5761
- [ ] https://github.com/SigNoz/signoz/issues/5701
- [ ] https://github.com/SigNoz/signoz/issues/5691
- [ ] https://github.com/SigNoz/signoz/issues/5681
- [ ] https://github.com/SigNoz/signoz/issues/5657
- [ ] https://github.com/SigNoz/signoz/issues/5653
- [ ] https://github.com/SigNoz/signoz/issues/5635
- [ ] https://github.com/SigNoz/signoz/issues/5633
- [ ] https://github.com/SigNoz/signoz/issues/5574
- [ ] https://github.com/SigNoz/signoz/issues/5488
- [ ] https://github.com/SigNoz/signoz/issues/5485
- [ ] https://github.com/SigNoz/signoz/issues/5484
- [ ] https://github.com/SigNoz/signoz/issues/5478
- [ ] https://github.com/SigNoz/signoz/issues/5397
- [ ] https://github.com/SigNoz/signoz/issues/5384
- [ ] https://github.com/SigNoz/signoz/issues/5380
- [ ] https://github.com/SigNoz/signoz/issues/5250
- [ ] https://github.com/SigNoz/signoz/issues/5208
- [ ] https://github.com/SigNoz/signoz/issues/5156
- [ ] https://github.com/SigNoz/signoz/issues/5144
- [ ] https://github.com/SigNoz/signoz/issues/5153
- [ ] https://github.com/SigNoz/signoz/issues/5136
- [ ] https://github.com/SigNoz/signoz/issues/5126
- [ ] https://github.com/SigNoz/signoz/issues/5039
- [ ] https://github.com/SigNoz/signoz/issues/5008
- [ ] https://github.com/SigNoz/signoz/issues/4984
- [ ] https://github.com/SigNoz/signoz/issues/4978
- [ ] https://github.com/SigNoz/signoz/issues/4933
- [ ] https://github.com/SigNoz/signoz/issues/4826
- [ ] https://github.com/SigNoz/signoz/issues/4782
- [ ] https://github.com/SigNoz/signoz/issues/4713
- [ ] https://github.com/SigNoz/signoz/issues/4683
- [ ] https://github.com/SigNoz/signoz/issues/4309
- [ ] https://github.com/SigNoz/signoz/issues/4109
- [ ] https://github.com/SigNoz/signoz/issues/3787
- [ ] https://github.com/SigNoz/signoz/issues/3786
- [ ] https://github.com/SigNoz/signoz/issues/3660
- [ ] https://github.com/SigNoz/signoz/issues/3617
- [ ] https://github.com/SigNoz/signoz/issues/3334
- [ ] https://github.com/SigNoz/signoz/issues/3289
- [ ] https://github.com/SigNoz/signoz/issues/3267
- [ ] https://github.com/SigNoz/signoz/issues/3204
- [ ] https://github.com/SigNoz/signoz/issues/3174
- [ ] https://github.com/SigNoz/signoz/issues/3151
- [ ] https://github.com/SigNoz/signoz/issues/3085
- [ ] https://github.com/SigNoz/signoz/issues/3043
- [ ] https://github.com/SigNoz/signoz/issues/2981
- [ ] https://github.com/SigNoz/signoz/issues/2976
- [ ] https://github.com/SigNoz/signoz/issues/2771
- [ ] https://github.com/SigNoz/signoz/issues/2767
- [ ] https://github.com/SigNoz/signoz/issues/2766
- [ ] https://github.com/SigNoz/signoz/issues/2173
- [ ] https://github.com/SigNoz/signoz/issues/1743
